[package]
name = "rust-image-seam-carver"
version = "0.1.0"
authors = ["Gerry Manoim <gerrymanoim@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
clap = "~2.33"
